### ISSUE TITLE
Erreur par pygamegui

### ISSUE THREAD

**Issue by Colveri** [e-psi-lon/Youtube-Downloader#1]
Erreur lors de la demande de preview de la vidéo.

Aucune idée si cela vient de moi ou si tu peux y faire quelque chosse.

```
Traceback (most recent call last):
  File "e:\Téléchargements\Youtube-Downloader-main\main.pyw", line 247, in <module>
    preview_launch()
  File "e:\Téléchargements\Youtube-Downloader-main\main.pyw", line 208, in preview_launch
    description.set_text(desc)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pygame_gui\elements\ui_text_box.py", line 1147, in set_text
    self._reparse_and_rebuild()
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pygame_gui\elements\ui_text_box.py", line 805, in _reparse_and_rebuild
    self.rebuild()
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pygame_gui\elements\ui_text_box.py", line 226, in rebuild
    self.parse_html_into_style_data()
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pygame_gui\elements\ui_text_box.py", line 560, in parse_html_into_style_data
    feed_input = self._pre_parse_text(translate(feed_input, **self.text_kwargs) + self.appended_text)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pygame_gui\core\utility.py", line 600, in translate
    return i18n.t(text_to_translate, **keywords)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\i18n\translator.py", line 26, in t
    resource_loader.search_translation(key, locale)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\i18n\resource_loader.py", line 97, in search_translation
    splitted_key = key.split(config.get('namespace_delimiter'))
                   ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by e-psi-lon** [comment]
T'as essayé de mettre à jour Pygame GUI ?

**Comment by Colveri** [comment]
> T'as essayé de mettre à jour Pygame GUI ?

Oui, c'est la toute dernière version. J'ai testé sur mon PC portable et il avait rien. Donc ça a installé directement.
Je te tiens au courant, je vais essayer de désinstaller réinstaller

**Comment by e-psi-lon** [comment]
Ok je te laisse voir
